service: winspect

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs10

functions:
  getParty:
    handler: src/lambdas/getParty.handler
    events:
      - http:
          method: get
          path: party
          integration: lambda
